/* =========================================================================
   SCHOOL RESULT PORTAL
   Plain JS + Supabase. No build step. Open index.html in a browser.

   Expected Supabase schema (run this in the Supabase SQL editor):

   -- profiles table links to Supabase Auth users and stores role/name
   create table profiles (
     id uuid primary key references auth.users(id) on delete cascade,
     name text not null,
     role text not null check (role in ('admin','teacher'))
   );

   create table grades (
     id serial primary key,
     name text not null
   );

   create table subjects (
     id serial primary key,
     name text not null
   );

   create table students (
     id serial primary key,
     student_code text not null,
     name text not null,
     grade_id int references grades(id)
   );

   create table grade_subjects (
     grade_id int references grades(id),
     subject_id int references subjects(id),
     primary key (grade_id, subject_id)
   );

   create table teacher_subjects (
     teacher_id uuid references profiles(id),
     subject_id int references subjects(id),
     primary key (teacher_id, subject_id)
   );

   create table marks (
     id serial primary key,
     student_id int references students(id),
     subject_id int references subjects(id),
     mark numeric,
     unique (student_id, subject_id)
   );

   create table teacher_comments (
     id serial primary key,
     student_id int references students(id),
     teacher_id uuid references profiles(id),
     comment text
   );

   create table school_settings (
     key text primary key,
     value text
   );

   -- Suggested school_settings rows:
   -- ('school_name', 'ABC School')
   -- ('logo_url', 'https://.../logo.png')
   -- ('principal_name', 'Principal Name')
   -- ('report_footer', 'Generated by School Result Portal')

   Row Level Security: enable RLS on all tables and add policies so that
   admins (profiles.role = 'admin') can do anything, and teachers can only
   read/write marks & comments for subjects listed in teacher_subjects for
   their own id. This file assumes such policies exist server-side; it does
   not attempt to enforce permissions on its own beyond hiding UI.
   ========================================================================= */

let db = null;
let currentUser = null;   // Supabase auth user
let currentProfile = null; // { id, name, role }
let schoolSettings = {};   // key -> value

// ---------------------------------------------------------------------
// Supabase credentials
// Paste your project's URL and anon public key here. The anon key is
// safe to put in client-side code — it's designed to be public. Real
// access control comes from the Row Level Security policies in setup.sql.
// Find both under: Supabase dashboard -> Project Settings -> API
// ---------------------------------------------------------------------
const SUPABASE_URL = 'https://vhferhuwbtfqekeyymow.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoZmVyaHV3YnRmcWVrZXl5bW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4NzgxNDcsImV4cCI6MjA5ODQ1NDE0N30.8RYwVnsc2mtncJ3_4eES_u-_0hXgsbQC3t5qttT_JBM';


function initSupabase() {
  if (!SUPABASE_URL || SUPABASE_URL.includes('YOUR-PROJECT-REF') ||
      !SUPABASE_ANON_KEY || SUPABASE_ANON_KEY.includes('YOUR-ANON')) {
    document.getElementById('config-screen').classList.remove('hidden');
    document.getElementById('config-error').textContent =
      'Supabase credentials are not set. Open app.js and fill in SUPABASE_URL and SUPABASE_ANON_KEY near the top of the file.';
    document.getElementById('config-error').classList.remove('hidden');
    return false;
  }
  if (!window.supabase || typeof window.supabase.createClient !== 'function') {
    document.getElementById('config-screen').classList.remove('hidden');
    document.getElementById('config-error').textContent =
      'The Supabase library failed to load from the CDN. Check your internet connection, ' +
      'disable any ad blocker for this page, then reload.';
    document.getElementById('config-error').classList.remove('hidden');
    return false;
  }
  try {
    db = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    return true;
  } catch (e) {
    document.getElementById('config-screen').classList.remove('hidden');
    document.getElementById('config-error').textContent = 'Could not connect: ' + e.message;
    document.getElementById('config-error').classList.remove('hidden');
    return false;
  }
}

// ---------------------------------------------------------------------
// Boot
// ---------------------------------------------------------------------
window.addEventListener('DOMContentLoaded', boot);

async function boot() {
  if (!initSupabase()) return;

  await loadSchoolSettings();
  applyBranding();

  const { data: { session } } = await db.auth.getSession();
  if (session && session.user) {
    currentUser = session.user;
    await loadProfileAndEnter();
  } else {
    showLogin();
  }

  db.auth.onAuthStateChange((event, session) => {
    if (event === 'SIGNED_OUT') {
      currentUser = null;
      currentProfile = null;
      showLogin();
    }
  });
}

async function loadSchoolSettings() {
  schoolSettings = {};
  try {
    const { data, error } = await db.from('school_settings').select('key,value');
    if (!error && data) {
      data.forEach(row => { schoolSettings[row.key] = row.value; });
    }
  } catch (e) { /* table may not exist yet; ignore */ }
}

function applyBranding() {
  const name = schoolSettings.school_name || 'School Result Portal';
  const logo = schoolSettings.logo_url || '';
  document.title = name;
  ['login-school-name', 'header-school-name'].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.textContent = name;
  });
  ['login-logo', 'header-logo'].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.src = logo || fallbackLogoDataUri();
  });
}

function fallbackLogoDataUri() {
  // Simple neutral placeholder logo (grey square with "S") so layout never breaks
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80">
    <rect width="80" height="80" fill="#e5e7eb"/>
    <text x="40" y="50" font-size="34" text-anchor="middle" fill="#888" font-family="Arial">S</text>
  </svg>`;
  return 'data:image/svg+xml;base64,' + btoa(svg);
}

// ---------------------------------------------------------------------
// Auth
// ---------------------------------------------------------------------
function showLogin() {
  document.getElementById('config-screen').classList.add('hidden');
  document.getElementById('login-wrap').classList.remove('hidden');
  document.getElementById('app-wrap').classList.add('hidden');
}

async function doLogin() {
  const email = document.getElementById('login-email').value.trim();
  const password = document.getElementById('login-password').value;
  const errEl = document.getElementById('login-error');
  errEl.classList.add('hidden');

  if (!email || !password) {
    errEl.textContent = 'Enter your email and password.';
    errEl.classList.remove('hidden');
    return;
  }

  const { data, error } = await db.auth.signInWithPassword({ email, password });
  if (error) {
    errEl.textContent = error.message;
    errEl.classList.remove('hidden');
    return;
  }
  currentUser = data.user;
  await loadProfileAndEnter();
}

async function doLogout() {
  await db.auth.signOut();
  currentUser = null;
  currentProfile = null;
  showLogin();
}

async function loadProfileAndEnter() {
  const { data, error } = await db
    .from('profiles')
    .select('id,name,role')
    .eq('id', currentUser.id)
    .single();

  if (error || !data) {
    document.getElementById('login-error').textContent =
      'Logged in, but no profile found for this account. Ask the admin to add you.';
    document.getElementById('login-error').classList.remove('hidden');
    document.getElementById('login-wrap').classList.remove('hidden');
    document.getElementById('app-wrap').classList.add('hidden');
    return;
  }

  currentProfile = data;
  enterApp();
}

function enterApp() {
  document.getElementById('config-screen').classList.add('hidden');
  document.getElementById('login-wrap').classList.add('hidden');
  document.getElementById('app-wrap').classList.remove('hidden');
  document.getElementById('header-user-name').textContent =
    currentProfile.name + ' (' + currentProfile.role + ')';

  if (currentProfile.role === 'admin') {
    document.getElementById('admin-panel').classList.remove('hidden');
    document.getElementById('teacher-panel').classList.add('hidden');
    renderAdminPanel();
  } else {
    document.getElementById('teacher-panel').classList.remove('hidden');
    document.getElementById('admin-panel').classList.add('hidden');
    renderTeacherPanel();
  }
}

// ---------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------
function showStatus(msg, isError) {
  const area = document.getElementById('status-area');
  const div = document.createElement('div');
  div.className = 'status-msg ' + (isError ? 'err' : 'ok');
  div.textContent = msg;
  area.innerHTML = '';
  area.appendChild(div);
  setTimeout(() => { div.remove(); }, 4000);
}

function el(tag, attrs, children) {
  const e = document.createElement(tag);
  if (attrs) {
    Object.keys(attrs).forEach(k => {
      if (k === 'class') e.className = attrs[k];
      else if (k === 'html') e.innerHTML = attrs[k];
      else if (k.startsWith('on')) e.addEventListener(k.slice(2), attrs[k]);
      else e.setAttribute(k, attrs[k]);
    });
  }
  (children || []).forEach(c => {
    if (typeof c === 'string') e.appendChild(document.createTextNode(c));
    else if (c) e.appendChild(c);
  });
  return e;
}

function letterGrade(mark) {
  const m = Number(mark);
  if (isNaN(m)) return '-';
  if (m >= 80) return 'A+';
  if (m >= 70) return 'A';
  if (m >= 60) return 'A-';
  if (m >= 50) return 'B';
  if (m >= 40) return 'C';
  if (m >= 33) return 'D';
  return 'F';
}

/* =========================================================================
   ADMIN PANEL
   Tabs: Students, Teachers, Grades & Subjects, Marks Overview, Settings, PDFs
   ========================================================================= */

let adminTab = 'students';
let adminCache = { grades: [], subjects: [], students: [], teachers: [], gradeSubjects: [], teacherSubjects: [] };

async function renderAdminPanel() {
  const root = document.getElementById('admin-panel');
  root.innerHTML = '';

  const tabs = el('div', { class: 'tabs' }, [
    tabBtn('students', 'Students'),
    tabBtn('teachers', 'Teachers'),
    tabBtn('subjects', 'Grades & Subjects'),
    tabBtn('marks', 'Marks Overview'),
    tabBtn('pdfs', 'Report Cards / PDFs'),
    tabBtn('settings', 'School Settings'),
  ]);
  root.appendChild(tabs);

  const body = el('div', { id: 'admin-tab-body' });
  root.appendChild(body);

  await loadAdminCache();
  renderAdminTabBody();
}

function tabBtn(key, label) {
  return el('button', {
    class: 'tab-btn' + (adminTab === key ? ' active' : ''),
    onclick: () => { adminTab = key; renderAdminPanel(); }
  }, [label]);
}

async function loadAdminCache() {
  const [g, s, st, tp, gs, ts] = await Promise.all([
    db.from('grades').select('*').order('id'),
    db.from('subjects').select('*').order('id'),
    db.from('students').select('*').order('id'),
    db.from('profiles').select('*').eq('role', 'teacher').order('name'),
    db.from('grade_subjects').select('*'),
    db.from('teacher_subjects').select('*'),
  ]);
  adminCache.grades = g.data || [];
  adminCache.subjects = s.data || [];
  adminCache.students = st.data || [];
  adminCache.teachers = tp.data || [];
  adminCache.gradeSubjects = gs.data || [];
  adminCache.teacherSubjects = ts.data || [];
}

function renderAdminTabBody() {
  const body = document.getElementById('admin-tab-body');
  body.innerHTML = '';
  if (adminTab === 'students') return renderStudentsTab(body);
  if (adminTab === 'teachers') return renderTeachersTab(body);
  if (adminTab === 'subjects') return renderGradesSubjectsTab(body);
  if (adminTab === 'marks') return renderMarksOverviewTab(body);
  if (adminTab === 'pdfs') return renderPdfTab(body);
  if (adminTab === 'settings') return renderSettingsTab(body);
}

/* ---------------- Students tab ---------------- */
function renderStudentsTab(body) {
  const card = el('div', { class: 'card' });
  card.appendChild(el('h2', {}, ['Students']));

  const gradeOptions = adminCache.grades.map(g => el('option', { value: g.id }, [g.name]));
  const form = el('div', { class: 'form-row' }, [
    field('Student code', 'new-student-code', 'text', 'e.g. G1-002'),
    field('Name', 'new-student-name', 'text', 'Full name'),
    selectField('Grade', 'new-student-grade', gradeOptions),
    el('button', { class: 'btn', onclick: addStudent }, ['Add student']),
  ]);
  card.appendChild(form);

  const wrap = el('div', { class: 'table-wrap' });
  const table = el('table');
  table.appendChild(el('tr', {}, [
    el('th', {}, ['Code']), el('th', {}, ['Name']), el('th', {}, ['Grade']), el('th', {}, [''])
  ]));
  adminCache.students.forEach(s => {
    const grade = adminCache.grades.find(g => g.id === s.grade_id);
    table.appendChild(el('tr', {}, [
      el('td', {}, [s.student_code]),
      el('td', {}, [s.name]),
      el('td', {}, [grade ? grade.name : '-']),
      el('td', {}, [el('button', { class: 'btn danger', onclick: () => deleteStudent(s.id) }, ['Delete'])]),
    ]));
  });
  wrap.appendChild(table);
  card.appendChild(wrap);
  body.appendChild(card);
}

function field(label, id, type, placeholder) {
  return el('div', { class: 'form-field' }, [
    el('label', { for: id }, [label]),
    el('input', { id, type, placeholder: placeholder || '' }),
  ]);
}
function selectField(label, id, options) {
  return el('div', { class: 'form-field' }, [
    el('label', { for: id }, [label]),
    el('select', { id }, options),
  ]);
}

async function addStudent() {
  const code = document.getElementById('new-student-code').value.trim();
  const name = document.getElementById('new-student-name').value.trim();
  const gradeId = document.getElementById('new-student-grade').value;
  if (!code || !name || !gradeId) { showStatus('Fill in all student fields.', true); return; }

  const { error } = await db.from('students').insert({
    student_code: code, name, grade_id: Number(gradeId)
  });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Student added.');
  await loadAdminCache();
  renderAdminTabBody();
}

async function deleteStudent(id) {
  if (!confirm('Delete this student? This also removes their marks and comments.')) return;
  await db.from('marks').delete().eq('student_id', id);
  await db.from('teacher_comments').delete().eq('student_id', id);
  const { error } = await db.from('students').delete().eq('id', id);
  if (error) { showStatus(error.message, true); return; }
  showStatus('Student deleted.');
  await loadAdminCache();
  renderAdminTabBody();
}

/* ---------------- Teachers tab ---------------- */
function renderTeachersTab(body) {
  const card = el('div', { class: 'card' });
  card.appendChild(el('h2', {}, ['Teachers']));
  card.appendChild(el('p', { class: 'muted small' }, [
    'Teacher accounts are created in Supabase Authentication, then linked here. ',
    'To add a teacher: create their login in Supabase Auth first, then add a row below with their user ID.'
  ]));

  const form = el('div', { class: 'form-row' }, [
    field('Supabase user ID', 'new-teacher-uid', 'text', 'uuid from Supabase Auth'),
    field('Name', 'new-teacher-name', 'text', 'Full name'),
    el('button', { class: 'btn', onclick: addTeacherProfile }, ['Add teacher']),
  ]);
  card.appendChild(form);

  const wrap = el('div', { class: 'table-wrap' });
  const table = el('table');
  table.appendChild(el('tr', {}, [
    el('th', {}, ['Name']), el('th', {}, ['Subjects']), el('th', {}, ['Assign subject']), el('th', {}, [''])
  ]));

  adminCache.teachers.forEach(t => {
    const mySubjectIds = adminCache.teacherSubjects.filter(ts => ts.teacher_id === t.id).map(ts => ts.subject_id);
    const subjNames = mySubjectIds.map(sid => {
      const s = adminCache.subjects.find(x => x.id === sid);
      return s ? s.name : '?';
    });

    const subjTags = el('td', {}, subjNames.length
      ? subjNames.map(n => el('span', { class: 'badge', style: 'margin-right:4px;' }, [n]))
      : [el('span', { class: 'muted small' }, ['None assigned'])]);

    const unassigned = adminCache.subjects.filter(s => !mySubjectIds.includes(s.id));
    const assignCell = el('td');
    if (unassigned.length) {
      const sel = el('select', { id: 'assign-sel-' + t.id },
        unassigned.map(s => el('option', { value: s.id }, [s.name])));
      const btn = el('button', {
        class: 'btn secondary',
        onclick: () => assignSubjectToTeacher(t.id, document.getElementById('assign-sel-' + t.id).value)
      }, ['Assign']);
      assignCell.appendChild(sel);
      assignCell.appendChild(btn);
    } else {
      assignCell.appendChild(el('span', { class: 'muted small' }, ['All subjects assigned']));
    }

    table.appendChild(el('tr', {}, [
      el('td', {}, [t.name]),
      subjTags,
      assignCell,
      el('td', {}, [el('button', { class: 'btn danger', onclick: () => removeTeacher(t.id) }, ['Remove'])]),
    ]));
  });

  wrap.appendChild(table);
  card.appendChild(wrap);
  body.appendChild(card);
}

async function addTeacherProfile() {
  const uid = document.getElementById('new-teacher-uid').value.trim();
  const name = document.getElementById('new-teacher-name').value.trim();
  if (!uid || !name) { showStatus('Fill in both fields.', true); return; }
  const { error } = await db.from('profiles').insert({ id: uid, name, role: 'teacher' });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Teacher added.');
  await loadAdminCache();
  renderAdminTabBody();
}

async function assignSubjectToTeacher(teacherId, subjectId) {
  const { error } = await db.from('teacher_subjects').insert({
    teacher_id: teacherId, subject_id: Number(subjectId)
  });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Subject assigned.');
  await loadAdminCache();
  renderAdminTabBody();
}

async function removeTeacher(id) {
  if (!confirm('Remove this teacher profile and subject assignments? Their login stays in Supabase Auth.')) return;
  await db.from('teacher_subjects').delete().eq('teacher_id', id);
  const { error } = await db.from('profiles').delete().eq('id', id);
  if (error) { showStatus(error.message, true); return; }
  showStatus('Teacher removed.');
  await loadAdminCache();
  renderAdminTabBody();
}

/* ---------------- Grades & Subjects tab ---------------- */
function renderGradesSubjectsTab(body) {
  const gCard = el('div', { class: 'card' });
  gCard.appendChild(el('h2', {}, ['Grades']));
  gCard.appendChild(el('div', { class: 'form-row' }, [
    field('New grade name', 'new-grade-name', 'text', 'e.g. Grade 3'),
    el('button', { class: 'btn', onclick: addGrade }, ['Add grade']),
  ]));
  const gTable = el('table');
  gTable.appendChild(el('tr', {}, [el('th', {}, ['Grade']), el('th', {}, [''])]));
  adminCache.grades.forEach(g => {
    gTable.appendChild(el('tr', {}, [
      el('td', {}, [g.name]),
      el('td', {}, [el('button', { class: 'btn danger', onclick: () => deleteGrade(g.id) }, ['Delete'])]),
    ]));
  });
  gCard.appendChild(el('div', { class: 'table-wrap' }, [gTable]));
  body.appendChild(gCard);

  const sCard = el('div', { class: 'card' });
  sCard.appendChild(el('h2', {}, ['Subjects']));
  sCard.appendChild(el('div', { class: 'form-row' }, [
    field('New subject name', 'new-subject-name', 'text', 'e.g. Arabic'),
    el('button', { class: 'btn', onclick: addSubject }, ['Add subject']),
  ]));
  const sTable = el('table');
  sTable.appendChild(el('tr', {}, [el('th', {}, ['Subject']), el('th', {}, [''])]));
  adminCache.subjects.forEach(s => {
    sTable.appendChild(el('tr', {}, [
      el('td', {}, [s.name]),
      el('td', {}, [el('button', { class: 'btn danger', onclick: () => deleteSubject(s.id) }, ['Delete'])]),
    ]));
  });
  sCard.appendChild(el('div', { class: 'table-wrap' }, [sTable]));
  body.appendChild(sCard);

  const gsCard = el('div', { class: 'card' });
  gsCard.appendChild(el('h2', {}, ['Which subjects belong to which grade']));
  gsCard.appendChild(el('p', { class: 'muted small' }, ['Add a subject to a grade below. No code changes needed when the school grows.']));

  const gradeOpts = adminCache.grades.map(g => el('option', { value: g.id }, [g.name]));
  const subjOpts = adminCache.subjects.map(s => el('option', { value: s.id }, [s.name]));
  gsCard.appendChild(el('div', { class: 'form-row' }, [
    selectField('Grade', 'gs-grade', gradeOpts),
    selectField('Subject', 'gs-subject', subjOpts),
    el('button', { class: 'btn', onclick: addGradeSubject }, ['Add mapping']),
  ]));

  const gsTable = el('table');
  gsTable.appendChild(el('tr', {}, [el('th', {}, ['Grade']), el('th', {}, ['Subject']), el('th', {}, [''])]));
  adminCache.gradeSubjects.forEach(row => {
    const g = adminCache.grades.find(x => x.id === row.grade_id);
    const s = adminCache.subjects.find(x => x.id === row.subject_id);
    gsTable.appendChild(el('tr', {}, [
      el('td', {}, [g ? g.name : '?']),
      el('td', {}, [s ? s.name : '?']),
      el('td', {}, [el('button', {
        class: 'btn danger',
        onclick: () => deleteGradeSubject(row.grade_id, row.subject_id)
      }, ['Remove'])]),
    ]));
  });
  gsCard.appendChild(el('div', { class: 'table-wrap' }, [gsTable]));
  body.appendChild(gsCard);
}

async function addGrade() {
  const name = document.getElementById('new-grade-name').value.trim();
  if (!name) return;
  const { error } = await db.from('grades').insert({ name });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Grade added.');
  await loadAdminCache(); renderAdminTabBody();
}
async function deleteGrade(id) {
  if (!confirm('Delete this grade? Students in this grade will need reassigning.')) return;
  const { error } = await db.from('grades').delete().eq('id', id);
  if (error) { showStatus(error.message, true); return; }
  showStatus('Grade deleted.');
  await loadAdminCache(); renderAdminTabBody();
}
async function addSubject() {
  const name = document.getElementById('new-subject-name').value.trim();
  if (!name) return;
  const { error } = await db.from('subjects').insert({ name });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Subject added.');
  await loadAdminCache(); renderAdminTabBody();
}
async function deleteSubject(id) {
  if (!confirm('Delete this subject? This also removes related marks, comments, and assignments.')) return;
  await db.from('marks').delete().eq('subject_id', id);
  await db.from('grade_subjects').delete().eq('subject_id', id);
  await db.from('teacher_subjects').delete().eq('subject_id', id);
  const { error } = await db.from('subjects').delete().eq('id', id);
  if (error) { showStatus(error.message, true); return; }
  showStatus('Subject deleted.');
  await loadAdminCache(); renderAdminTabBody();
}
async function addGradeSubject() {
  const gradeId = document.getElementById('gs-grade').value;
  const subjectId = document.getElementById('gs-subject').value;
  if (!gradeId || !subjectId) return;
  const { error } = await db.from('grade_subjects').insert({
    grade_id: Number(gradeId), subject_id: Number(subjectId)
  });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Mapping added.');
  await loadAdminCache(); renderAdminTabBody();
}
async function deleteGradeSubject(gradeId, subjectId) {
  const { error } = await db.from('grade_subjects')
    .delete().eq('grade_id', gradeId).eq('subject_id', subjectId);
  if (error) { showStatus(error.message, true); return; }
  showStatus('Mapping removed.');
  await loadAdminCache(); renderAdminTabBody();
}

/* ---------------- Marks overview tab (admin, read/edit all) ---------------- */
async function renderMarksOverviewTab(body) {
  const card = el('div', { class: 'card' });
  card.appendChild(el('h2', {}, ['Marks overview']));

  const gradeOpts = adminCache.grades.map(g => el('option', { value: g.id }, [g.name]));
  const gradeSelect = el('select', { id: 'marks-grade-select' }, gradeOpts);
  gradeSelect.addEventListener('change', () => loadAndRenderMarksGrid());

  card.appendChild(el('div', { class: 'form-row' }, [
    el('div', { class: 'form-field' }, [
      el('label', {}, ['Grade']),
      gradeSelect
    ])
  ]));

  const gridWrap = el('div', { id: 'marks-grid-wrap' });
  card.appendChild(gridWrap);
  body.appendChild(card);

  if (adminCache.grades.length) await loadAndRenderMarksGrid();
}

async function loadAndRenderMarksGrid() {
  const gradeId = Number(document.getElementById('marks-grade-select').value);
  const gridWrap = document.getElementById('marks-grid-wrap');
  gridWrap.innerHTML = 'Loading...';

  const students = adminCache.students.filter(s => s.grade_id === gradeId);
  const subjectIds = adminCache.gradeSubjects.filter(gs => gs.grade_id === gradeId).map(gs => gs.subject_id);
  const subjects = adminCache.subjects.filter(s => subjectIds.includes(s.id));

  const { data: marksData } = await db
    .from('marks')
    .select('*')
    .in('student_id', students.map(s => s.id).length ? students.map(s => s.id) : [-1]);

  const marksMap = {};
  (marksData || []).forEach(m => { marksMap[m.student_id + '-' + m.subject_id] = m.mark; });

  gridWrap.innerHTML = '';
  if (!students.length || !subjects.length) {
    gridWrap.appendChild(el('p', { class: 'muted' }, ['No students or subjects set up for this grade yet.']));
    return;
  }

  const table = el('table');
  table.appendChild(el('tr', {}, [
    el('th', {}, ['Student']),
    ...subjects.map(s => el('th', {}, [s.name]))
  ]));
  students.forEach(stu => {
    const row = el('tr', {}, [el('td', {}, [stu.name + ' (' + stu.student_code + ')'])]);
    subjects.forEach(subj => {
      const key = stu.id + '-' + subj.id;
      const input = el('input', {
        type: 'number', value: marksMap[key] != null ? marksMap[key] : '',
        id: 'am-' + key
      });
      row.appendChild(el('td', {}, [input]));
    });
    table.appendChild(row);
  });
  gridWrap.appendChild(el('div', { class: 'table-wrap' }, [table]));
  gridWrap.appendChild(el('button', {
    class: 'btn', style: 'margin-top:10px;',
    onclick: () => saveMarksGrid(students, subjects)
  }, ['Save all marks']));
}

async function saveMarksGrid(students, subjects) {
  const rows = [];
  students.forEach(stu => {
    subjects.forEach(subj => {
      const key = stu.id + '-' + subj.id;
      const val = document.getElementById('am-' + key).value;
      if (val !== '') rows.push({ student_id: stu.id, subject_id: subj.id, mark: Number(val) });
    });
  });
  if (!rows.length) { showStatus('No marks entered.', true); return; }
  const { error } = await db.from('marks').upsert(rows, { onConflict: 'student_id,subject_id' });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Marks saved.');
}

/* ---------------- Settings tab ---------------- */
function renderSettingsTab(body) {
  const card = el('div', { class: 'card' });
  card.appendChild(el('h2', {}, ['School settings']));
  card.appendChild(el('p', { class: 'muted small' }, ['These appear on every page and every report card.']));

  const keys = [
    { key: 'school_name', label: 'School name' },
    { key: 'logo_url', label: 'Logo URL (image link)' },
    { key: 'principal_name', label: 'Principal name' },
    { key: 'report_footer', label: 'Report card footer text' },
  ];

  keys.forEach(k => {
    card.appendChild(el('div', { class: 'form-row' }, [
      el('div', { class: 'form-field', style: 'flex:1;min-width:260px;' }, [
        el('label', {}, [k.label]),
        el('input', { id: 'setting-' + k.key, type: 'text', value: schoolSettings[k.key] || '' }),
      ]),
    ]));
  });

  card.appendChild(el('button', { class: 'btn', onclick: saveSettings }, ['Save settings']));

  const infoBox = el('div', { style: 'margin-top:24px;border-top:1px solid #eee;padding-top:14px;' }, [
    el('p', { class: 'muted small' }, ['Connected Supabase project: ' + SUPABASE_URL]),
    el('p', { class: 'muted small' }, ['To change project, edit SUPABASE_URL and SUPABASE_ANON_KEY at the top of app.js.']),
  ]);
  card.appendChild(infoBox);

  body.appendChild(card);
}

async function saveSettings() {
  const keys = ['school_name', 'logo_url', 'principal_name', 'report_footer'];
  const rows = keys.map(k => ({ key: k, value: document.getElementById('setting-' + k).value }));
  const { error } = await db.from('school_settings').upsert(rows, { onConflict: 'key' });
  if (error) { showStatus(error.message, true); return; }
  showStatus('Settings saved.');
  await loadSchoolSettings();
  applyBranding();
}

/* =========================================================================
   PDF GENERATION (report cards + internal marksheets)
   Uses hidden #report-render-area + html2canvas-free approach via jsPDF's
   html() method, which rasterizes the DOM node directly.
   ========================================================================= */

function renderPdfTab(body) {
  const card = el('div', { class: 'card' });
  card.appendChild(el('h2', {}, ['Report cards & marksheets']));

  // Single student report card
  const single = el('div', { style: 'margin-bottom:20px;' });
  single.appendChild(el('h3', {}, ['Single student report card']));
  const studentOpts = adminCache.students.map(s => {
    const g = adminCache.grades.find(gr => gr.id === s.grade_id);
    return el('option', { value: s.id }, [s.name + ' (' + s.student_code + (g ? ', ' + g.name : '') + ')']);
  });
  const studentSelect = el('select', { id: 'pdf-student-select' }, studentOpts);
  single.appendChild(el('div', { class: 'form-row' }, [
    el('div', { class: 'form-field' }, [el('label', {}, ['Student']), studentSelect]),
    el('button', { class: 'btn', onclick: generateSingleReportCard }, ['Generate report card PDF']),
  ]));
  card.appendChild(single);

  // Whole-grade report cards
  const bulk = el('div', { style: 'margin-bottom:20px;border-top:1px solid #eee;padding-top:16px;' });
  bulk.appendChild(el('h3', {}, ['All report cards for a grade']));
  const gradeOpts = adminCache.grades.map(g => el('option', { value: g.id }, [g.name]));
  const gradeSelect = el('select', { id: 'pdf-grade-select' }, gradeOpts);
  bulk.appendChild(el('div', { class: 'form-row' }, [
    el('div', { class: 'form-field' }, [el('label', {}, ['Grade']), gradeSelect]),
    el('button', { class: 'btn', onclick: generateGradeReportCards }, ['Generate all report cards']),
  ]));
  card.appendChild(bulk);

  // Internal marksheet
  const internal = el('div', { style: 'border-top:1px solid #eee;padding-top:16px;' });
  internal.appendChild(el('h3', {}, ['Internal marksheet (all grades)']));
  internal.appendChild(el('p', { class: 'muted small' }, ['Not for students — a compact table per grade for staff use.']));
  internal.appendChild(el('button', { class: 'btn', onclick: generateInternalMarksheet }, ['Generate internal marksheet']));
  card.appendChild(internal);

  const progress = el('div', { id: 'pdf-progress', class: 'muted small', style: 'margin-top:10px;' });
  card.appendChild(progress);

  body.appendChild(card);
}

async function fetchStudentReportData(studentId) {
  const student = adminCache.students.find(s => s.id === Number(studentId));
  if (!student) return null;
  const grade = adminCache.grades.find(g => g.id === student.grade_id);
  const subjectIds = adminCache.gradeSubjects.filter(gs => gs.grade_id === student.grade_id).map(gs => gs.subject_id);
  const subjects = adminCache.subjects.filter(s => subjectIds.includes(s.id));

  const { data: marks } = await db.from('marks').select('*').eq('student_id', student.id);
  const { data: comments } = await db.from('teacher_comments').select('*').eq('student_id', student.id);

  const marksBySubject = {};
  (marks || []).forEach(m => { marksBySubject[m.subject_id] = m.mark; });

  const commentText = (comments && comments.length)
    ? comments.map(c => c.comment).join(' ')
    : 'No comments added yet.';

  return { student, grade, subjects, marksBySubject, commentText };
}

function buildReportCardHtml(reportData) {
  const { student, grade, subjects, marksBySubject, commentText } = reportData;
  const logo = schoolSettings.logo_url || fallbackLogoDataUri();
  const schoolName = schoolSettings.school_name || 'School';
  const principal = schoolSettings.principal_name || 'Principal';
  const footer = schoolSettings.report_footer || '';

  const rows = subjects.map(s => {
    const mark = marksBySubject[s.id];
    return `<tr>
      <td>${escapeHtml(s.name)}</td>
      <td>${mark != null ? mark : '-'}</td>
      <td>${mark != null ? letterGrade(mark) : '-'}</td>
    </tr>`;
  }).join('');

  return `
  <div class="rc-page">
    <div class="rc-header">
      <img src="${logo}" onerror="this.style.display='none'">
      <div class="rc-school-name">${escapeHtml(schoolName)}</div>
      <div class="rc-title">REPORT CARD</div>
    </div>
    <div class="rc-meta">
      <div><strong>Student:</strong> ${escapeHtml(student.name)}</div>
      <div><strong>Code:</strong> ${escapeHtml(student.student_code)}</div>
      <div><strong>Grade:</strong> ${grade ? escapeHtml(grade.name) : '-'}</div>
    </div>
    <table class="rc-table">
      <tr><th>Subject</th><th>Mark</th><th>Grade</th></tr>
      ${rows || '<tr><td colspan="3">No marks recorded yet.</td></tr>'}
    </table>
    <div><strong>Teacher Comment</strong></div>
    <div class="rc-comment-box">${escapeHtml(commentText)}</div>
    <div class="rc-sign-row">
      <div>Class Teacher Signature</div>
      <div>${escapeHtml(principal)} — Principal Signature</div>
    </div>
    <div class="rc-footer">${escapeHtml(footer)}</div>
  </div>`;
}

function escapeHtml(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#039;');
}

/* ---------------------------------------------------------------------
   PDF helpers: jsPDF's .html() is unreliable when called repeatedly on
   the same doc across a loop with addPage() — later pages frequently
   come out blank or duplicate the first page. The reliable pattern is:
   render EACH page as its own single-page PDF, then merge all of them
   together with pdf-lib. This is what the "Generate all" buttons use.
   --------------------------------------------------------------------- */

// Renders one HTML node into a brand-new single-page PDF and returns its bytes.
async function renderHtmlToPdfBytes(htmlNode) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF('p', 'pt', 'a4');
  await doc.html(htmlNode, {
    x: 20, y: 20,
    html2canvas: { scale: 0.8 }
  });
  return doc.output('arraybuffer');
}

// Merges an array of single-page PDF byte buffers into one PDF and triggers a download.
async function mergePdfBuffersAndDownload(pdfBuffers, filename) {
  if (!window.PDFLib) {
    alert('pdf-lib failed to load. Check your internet connection or script URL.');
    return;
  }

  const { PDFDocument } = window.PDFLib;

  const mergedPdf = await PDFDocument.create();

  for (const buffer of pdfBuffers) {
    const src = await PDFDocument.load(buffer);
    const copiedPages = await mergedPdf.copyPages(src, src.getPageIndices());
    copiedPages.forEach(page => mergedPdf.addPage(page));
  }

  const mergedBytes = await mergedPdf.save();
  const blob = new Blob([mergedBytes], { type: 'application/pdf' });

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();

  URL.revokeObjectURL(url);
}

async function generateSingleReportCard() {
  const studentId = document.getElementById('pdf-student-select').value;
  const progress = document.getElementById('pdf-progress');
  progress.textContent = 'Generating...';

  const reportData = await fetchStudentReportData(studentId);
  if (!reportData) { progress.textContent = 'Student not found.'; return; }

  const renderArea = document.getElementById('report-render-area');
  renderArea.innerHTML = buildReportCardHtml(reportData);

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF('p', 'pt', 'a4');
  await doc.html(renderArea.firstElementChild, {
    x: 20, y: 20,
    html2canvas: { scale: 0.8 }
  });
  doc.save(reportData.student.name.replace(/\s+/g, '_') + '_Report.pdf');
  renderArea.innerHTML = '';
  progress.textContent = 'Done: ' + reportData.student.name + '_Report.pdf';
}

async function generateGradeReportCards() {
  const gradeId = Number(document.getElementById('pdf-grade-select').value);
  const grade = adminCache.grades.find(g => g.id === gradeId);
  const students = adminCache.students.filter(s => s.grade_id === gradeId);
  const progress = document.getElementById('pdf-progress');

  if (!students.length) { progress.textContent = 'No students in this grade.'; return; }

  const renderArea = document.getElementById('report-render-area');
  const pdfBuffers = [];

  for (let i = 0; i < students.length; i++) {
    progress.textContent = `Generating ${i + 1} of ${students.length}: ${students[i].name}...`;
    const reportData = await fetchStudentReportData(students[i].id);
    renderArea.innerHTML = buildReportCardHtml(reportData);
    const bytes = await renderHtmlToPdfBytes(renderArea.firstElementChild);
    pdfBuffers.push(bytes);
  }
  renderArea.innerHTML = '';

  progress.textContent = 'Combining into one file...';
  await mergePdfBuffersAndDownload(
    pdfBuffers,
    (grade ? grade.name.replace(/\s+/g, '') : 'Grade') + '_ReportCards.pdf'
  );
  progress.textContent = `Done: ${students.length} report cards for ` + (grade ? grade.name : 'grade') + '.';
}

async function generateInternalMarksheet() {
  const progress = document.getElementById('pdf-progress');
  progress.textContent = 'Generating internal marksheet...';

  const renderArea = document.getElementById('report-render-area');
  const pdfBuffers = [];

  for (const grade of adminCache.grades) {
    const students = adminCache.students.filter(s => s.grade_id === grade.id);
    const subjectIds = adminCache.gradeSubjects.filter(gs => gs.grade_id === grade.id).map(gs => gs.subject_id);
    const subjects = adminCache.subjects.filter(s => subjectIds.includes(s.id));
    if (!students.length || !subjects.length) continue;

    const { data: marks } = await db
      .from('marks').select('*').in('student_id', students.map(s => s.id));
    const marksMap = {};
    (marks || []).forEach(m => { marksMap[m.student_id + '-' + m.subject_id] = m.mark; });

    const headerCells = subjects.map(s => `<th>${escapeHtml(s.name)}</th>`).join('');
    const bodyRows = students.map(stu => {
      const cells = subjects.map(subj => {
        const v = marksMap[stu.id + '-' + subj.id];
        return `<td>${v != null ? v : '-'}</td>`;
      }).join('');
      return `<tr><td>${escapeHtml(stu.name)}</td>${cells}</tr>`;
    }).join('');

    const html = `
      <div class="rc-page" style="border:none;padding:20px;">
        <div class="rc-header" style="border-bottom:1px solid #333;">
          <div class="rc-school-name">${escapeHtml(schoolSettings.school_name || 'School')}</div>
          <div class="rc-title">${escapeHtml(grade.name.toUpperCase())} — INTERNAL MARKSHEET</div>
        </div>
        <table class="rc-table">
          <tr><th>Student</th>${headerCells}</tr>
          ${bodyRows}
        </table>
      </div>`;

    renderArea.innerHTML = html;
    const bytes = await renderHtmlToPdfBytes(renderArea.firstElementChild);
    pdfBuffers.push(bytes);
  }

  renderArea.innerHTML = '';

  if (!pdfBuffers.length) {
    progress.textContent = 'No grades with both students and subjects set up yet.';
    return;
  }

  progress.textContent = 'Combining into one file...';
  await mergePdfBuffersAndDownload(pdfBuffers, 'Internal_Marksheet.pdf');
  progress.textContent = 'Done: Internal_Marksheet.pdf';
}


/* =========================================================================
   TEACHER PANEL
   Teachers only see students in grades where their assigned subjects apply,
   restricted to their own subjects. Enforced here in the UI; enforce again
   with Supabase Row Level Security policies server-side for real security.
   ========================================================================= */

let teacherCache = { mySubjects: [], grades: [], students: [], gradeSubjects: [] };

async function renderTeacherPanel() {
  const root = document.getElementById('teacher-panel');
  root.innerHTML = 'Loading...';

  const { data: ts } = await db.from('teacher_subjects').select('subject_id').eq('teacher_id', currentProfile.id);
  const subjectIds = (ts || []).map(r => r.subject_id);

  const [subjRes, gradeRes, studentRes, gsRes] = await Promise.all([
    db.from('subjects').select('*').in('id', subjectIds.length ? subjectIds : [-1]),
    db.from('grades').select('*'),
    db.from('students').select('*'),
    db.from('grade_subjects').select('*').in('subject_id', subjectIds.length ? subjectIds : [-1]),
  ]);

  teacherCache.mySubjects = subjRes.data || [];
  teacherCache.grades = gradeRes.data || [];
  teacherCache.students = studentRes.data || [];
  teacherCache.gradeSubjects = gsRes.data || [];

  root.innerHTML = '';

  if (!teacherCache.mySubjects.length) {
    root.appendChild(el('div', { class: 'card' }, [
      el('p', {}, ['No subjects have been assigned to you yet. Ask the admin to assign a subject.'])
    ]));
    return;
  }

  const card = el('div', { class: 'card' });
  card.appendChild(el('h2', {}, ['Your subjects: ' + teacherCache.mySubjects.map(s => s.name).join(', ')]));

  const subjOpts = teacherCache.mySubjects.map(s => el('option', { value: s.id }, [s.name]));
  const subjSelect = el('select', { id: 'teacher-subject-select' }, subjOpts);
  subjSelect.addEventListener('change', renderTeacherMarksGrid);
  card.appendChild(el('div', { class: 'form-row' }, [
    el('div', { class: 'form-field' }, [el('label', {}, ['Subject']), subjSelect])
  ]));

  const gridWrap = el('div', { id: 'teacher-marks-grid' });
  card.appendChild(gridWrap);
  root.appendChild(card);

  await renderTeacherMarksGrid();

  // Report card generation for teacher's own students
  const pdfCard = el('div', { class: 'card' });
  pdfCard.appendChild(el('h2', {}, ['Generate report cards']));
  pdfCard.appendChild(el('p', { class: 'muted small' }, ['Generates report cards for students in grades you teach, using all subjects for that grade.']));

  const relevantGradeIds = [...new Set(teacherCache.gradeSubjects.map(gs => gs.grade_id))];
  const relevantGrades = teacherCache.grades.filter(g => relevantGradeIds.includes(g.id));
  const gOpts = relevantGrades.map(g => el('option', { value: g.id }, [g.name]));
  const gSelect = el('select', { id: 'teacher-pdf-grade' }, gOpts);

  pdfCard.appendChild(el('div', { class: 'form-row' }, [
    el('div', { class: 'form-field' }, [el('label', {}, ['Grade']), gSelect]),
    el('button', { class: 'btn', onclick: teacherGenerateGradeReportCards }, ['Generate report cards for this grade']),
  ]));
  pdfCard.appendChild(el('div', { id: 'teacher-pdf-progress', class: 'muted small' }));
  root.appendChild(pdfCard);
}

async function renderTeacherMarksGrid() {
  const subjectId = Number(document.getElementById('teacher-subject-select').value);
  const gridWrap = document.getElementById('teacher-marks-grid');
  gridWrap.innerHTML = 'Loading...';

  const gradeIdsForSubject = teacherCache.gradeSubjects
    .filter(gs => gs.subject_id === subjectId).map(gs => gs.grade_id);
  const students = teacherCache.students.filter(s => gradeIdsForSubject.includes(s.grade_id));

  if (!students.length) {
    gridWrap.innerHTML = '';
    gridWrap.appendChild(el('p', { class: 'muted' }, ['No students found for this subject yet.']));
    return;
  }

  const { data: marks } = await db
    .from('marks').select('*').eq('subject_id', subjectId).in('student_id', students.map(s => s.id));
  const { data: comments } = await db
    .from('teacher_comments').select('*').eq('teacher_id', currentProfile.id).in('student_id', students.map(s => s.id));

  const marksMap = {};
  (marks || []).forEach(m => { marksMap[m.student_id] = m.mark; });
  const commentMap = {};
  (comments || []).forEach(c => { commentMap[c.student_id] = c.comment; });

  gridWrap.innerHTML = '';
  const table = el('table');
  table.appendChild(el('tr', {}, [
    el('th', {}, ['Student']), el('th', {}, ['Mark']), el('th', {}, ['Comment'])
  ]));
  students.forEach(stu => {
    const markInput = el('input', {
      type: 'number', value: marksMap[stu.id] != null ? marksMap[stu.id] : '',
      id: 'tm-mark-' + stu.id
    });
    const commentInput = el('input', {
      type: 'text', style: 'width:220px;', value: commentMap[stu.id] || '',
      id: 'tm-comment-' + stu.id
    });
    table.appendChild(el('tr', {}, [
      el('td', {}, [stu.name + ' (' + stu.student_code + ')']),
      el('td', {}, [markInput]),
      el('td', {}, [commentInput]),
    ]));
  });
  gridWrap.appendChild(el('div', { class: 'table-wrap' }, [table]));
  gridWrap.appendChild(el('button', {
    class: 'btn', style: 'margin-top:10px;',
    onclick: () => saveTeacherMarks(students, subjectId)
  }, ['Save marks & comments']));
}

async function saveTeacherMarks(students, subjectId) {
  const markRows = [];
  const commentRows = [];
  students.forEach(stu => {
    const markVal = document.getElementById('tm-mark-' + stu.id).value;
    const commentVal = document.getElementById('tm-comment-' + stu.id).value.trim();
    if (markVal !== '') markRows.push({ student_id: stu.id, subject_id: subjectId, mark: Number(markVal) });
    if (commentVal !== '') commentRows.push({ student_id: stu.id, teacher_id: currentProfile.id, comment: commentVal });
  });

  if (markRows.length) {
    const { error } = await db.from('marks').upsert(markRows, { onConflict: 'student_id,subject_id' });
    if (error) { showStatus(error.message, true); return; }
  }
  for (const row of commentRows) {
    const { data: existing } = await db.from('teacher_comments')
      .select('id').eq('student_id', row.student_id).eq('teacher_id', row.teacher_id).maybeSingle();
    if (existing) {
      await db.from('teacher_comments').update({ comment: row.comment }).eq('id', existing.id);
    } else {
      await db.from('teacher_comments').insert(row);
    }
  }
  showStatus('Marks and comments saved.');
}

async function teacherGenerateGradeReportCards() {
  const gradeId = Number(document.getElementById('teacher-pdf-grade').value);
  const grade = teacherCache.grades.find(g => g.id === gradeId);
  const students = teacherCache.students.filter(s => s.grade_id === gradeId);
  const progress = document.getElementById('teacher-pdf-progress');

  if (!students.length) { progress.textContent = 'No students in this grade.'; return; }

  // Need full subject list + grade_subjects for this grade (not just teacher's own subjects)
  const { data: allGradeSubjects } = await db.from('grade_subjects').select('*').eq('grade_id', gradeId);
  const subjectIds = (allGradeSubjects || []).map(r => r.subject_id);
  const { data: allSubjects } = await db.from('subjects').select('*').in('id', subjectIds.length ? subjectIds : [-1]);

  const renderArea = document.getElementById('report-render-area');
  const pdfBuffers = [];

  for (let i = 0; i < students.length; i++) {
    progress.textContent = `Generating ${i + 1} of ${students.length}: ${students[i].name}...`;
    const student = students[i];

    const { data: marks } = await db.from('marks').select('*').eq('student_id', student.id);
    const { data: comments } = await db.from('teacher_comments').select('*').eq('student_id', student.id);
    const marksBySubject = {};
    (marks || []).forEach(m => { marksBySubject[m.subject_id] = m.mark; });
    const commentText = (comments && comments.length) ? comments.map(c => c.comment).join(' ') : 'No comments added yet.';

    const reportData = { student, grade, subjects: allSubjects || [], marksBySubject, commentText };
    renderArea.innerHTML = buildReportCardHtml(reportData);
    const bytes = await renderHtmlToPdfBytes(renderArea.firstElementChild);
    pdfBuffers.push(bytes);
  }

  renderArea.innerHTML = '';

  progress.textContent = 'Combining into one file...';
  await mergePdfBuffersAndDownload(
    pdfBuffers,
    (grade ? grade.name.replace(/\s+/g, '') : 'Grade') + '_ReportCards.pdf'
  );
  progress.textContent = `Done: ${students.length} report cards for ` + (grade ? grade.name : 'grade') + '.';
}
